// <auto-generated />
using KeyboardRemapping.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeyboardRemapping.Api.Migrations
{
    [DbContext(typeof(KeyboardDbContext))]
    partial class KeyboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("KeyboardRemapping.Api.Models.KeyMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyboardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceKeyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetKeyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceKeyId");

                    b.HasIndex("TargetKeyId");

                    b.HasIndex("KeyboardId", "SourceKeyId")
                        .IsUnique();

                    b.ToTable("KeyMappings");
                });

            modelBuilder.Entity("KeyboardRemapping.Api.Models.Keyboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Keyboards");
                });

            modelBuilder.Entity("KeyboardRemapping.Api.Models.KeyboardKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HidUsageCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyboardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyboardId", "HidUsageCode")
                        .IsUnique();

                    b.ToTable("KeyboardKeys");
                });

            modelBuilder.Entity("KeyboardRemapping.Api.Models.KeyMapping", b =>
                {
                    b.HasOne("KeyboardRemapping.Api.Models.Keyboard", "Keyboard")
                        .WithMany()
                        .HasForeignKey("KeyboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyboardRemapping.Api.Models.KeyboardKey", "SourceKey")
                        .WithMany("SourceMappings")
                        .HasForeignKey("SourceKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeyboardRemapping.Api.Models.KeyboardKey", "TargetKey")
                        .WithMany("TargetMappings")
                        .HasForeignKey("TargetKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Keyboard");

                    b.Navigation("SourceKey");

                    b.Navigation("TargetKey");
                });

            modelBuilder.Entity("KeyboardRemapping.Api.Models.KeyboardKey", b =>
                {
                    b.HasOne("KeyboardRemapping.Api.Models.Keyboard", "Keyboard")
                        .WithMany("Keys")
                        .HasForeignKey("KeyboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyboard");
                });

            modelBuilder.Entity("KeyboardRemapping.Api.Models.Keyboard", b =>
                {
                    b.Navigation("Keys");
                });

            modelBuilder.Entity("KeyboardRemapping.Api.Models.KeyboardKey", b =>
                {
                    b.Navigation("SourceMappings");

                    b.Navigation("TargetMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
